apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: loops-
spec:
  entrypoint: loop-example
  templates:
  - name: loop-example
    steps:
    - - name: cal-message
        template: http
        arguments:
         parameters: [{name: url, value: "https://8e3c-2405-201-5001-9051-b42f-f844-be-e63d.in.ngrok.io/multiply?number={{item}}"}]    
        withItems:
        - 1
        - 2

    - - name: step2
        template: echo
        arguments:
          parameters:
          - name: message 
            value: '{{steps.cal-message.outputs.result}}'

  
  - name: cal-no
    inputs:
      parameters:
      - name: number
    container:
      image: alpine:latest
      command: [sh, -c]
      args: ["echo {{inputs.parameters.number}}"]

  - name: echo
    inputs:
      parameters:
        - name: message
    container:
      image: 'docker/whalesay:latest'
      command:
        - cowsay
      args:
        - '{{inputs.parameters.message}}'

  # - name: http
  #   inputs:
  #     parameters:
  #       - name: url
  #   outputs:
  #     parameters:
  #       - name: result
  #         value: '{{response.body}}'
  #   http:
  #     url: "{{inputs.parameters.url}}"
