apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: retry-backoff-
spec:
  entrypoint: retry-backoff
  templates:
  - name: retry-backoff
    dag:
      tasks:
      - name: postfirstname
        template: postfirstname
      - name: getfullname
        template: getfullname
        depends: 'postfirstname'
        arguments:
          parameters:         
            - name: first_name
              value: '{{tasks.postfirstname.outputs.result}}'
            - name: last_name
              value: 'Gupta' 
      - name: echofullname
        template: echo
        depends: 'getfullname'
        arguments:
          parameters:         
            - name: name
              value: '{{tasks.getfullname.outputs.result}}'


  - name: postfirstname
    retryStrategy:
      limit: "3"
      backoff:
        duration: "1"       # Must be a string. Default unit is seconds. Could also be a Duration, e.g.: "2m", "6h", "1d"
        factor: "2"
        maxDuration: "3m" # Must be a string. Default unit is seconds. Could also be a Duration, e.g.: "2m", "6h", "1d"
    http:
      method: GET
      url: "https://8087-2405-201-5001-909e-fc64-dd1e-5038-2d4e.in.ngrok.io/postfirstname"
      body: '{"first_name":"Neha"}'


  - name: getfullname
    retryStrategy:
      limit: "10"
      backoff:
        duration: "1m"       # Must be a string. Default unit is seconds. Could also be a Duration, e.g.: "2m", "6h", "1d"
        factor: "2"
        maxDuration: "20m" # Must be a string. Default unit is seconds. Could also be a Duration, e.g.: "2m", "6h", "1d"
    inputs:
      parameters:
      - name: first_name
      - name: last_name
    http:
      method: GET
      url: "https://8087-2405-201-5001-909e-fc64-dd1e-5038-2d4e.in.ngrok.io/getfullnamehandler"
      body: '{"first_name":"{{inputs.parameters.first_name}}","last_name":"{{inputs.parameters.last_name}}"}' 

  - name: echo
    inputs:
      parameters:
      - name: name
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["{{inputs.parameters.name}}"]